server.port=8080

management.endpoints.enabled-by-default=true
management.endpoints.web.exposure.include=*

management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true


logging.level.org.springframework.web=DEBUG