spring:
    application:
     name: licensing-service 
    profiles:
      active: dev
    cloud:
        config: 
            uri: http://configserver:8071
    config:
      import: "optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://configserver:8071}"